name: 'Pull Request title checker'
description: 'Checks that the Pull Request title starts with a Jira ticket'
inputs:
  jira-project-key:
    description: 'The Jira project key of the repository (i.e. SYC)'
    required: true
  no-ticket-prefix:
    description: 'The prefix allowed for Pull Requests without a Jira ticket (i.e. NoTicket)'
    required: false
  ignore-case:
    description: 'Whether to do a case insensitive check or not'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'